name: don't shoot
slogan: 'spiele. jeden tag. nur 2 minuten.'
markdown: redcarpet
pygments: true
safe: true
lsi: false
timezone: Europe/Vienna
permalink: /:categories/:title

paginate: 3
paginate_path: "/p:num"