name: don't shoot
slogan: 'heir today, gone tomorrow'
markdown: redcarpet
pygments: true
safe: true
lsi: false
timezone: Europe/Vienna
permalink: /:categories/:title

paginate: 5
paginate_path: "/p:num"